add tests and fix coding style issues in tests
danirus/django-comments-xtd pull request #385
Opened 2022-09-20 22:35 UTC by JanMalte

2022-09-22 16:23 UTC, danirus commented
Thanks for this. Sorry that I didn't answer yet.
I'm a bit busy during the week. I hope I can get some time tomorrow to take a look.

2022-09-22 19:59 UTC, JanMalte commented
No stress. These are all not important changes.

2022-09-23 04:03 UTC, danirus requested changes
Thanks for the patience to fix all these details, some of them, now that I have seen them, make feel a little ashamed. It's great that you added new tests.

Only one detail, I think you don't want the file `.python-version` in the repository. As soon as your remove it, it can be merged.

2023-01-10 16:49 UTC, danirus approved these changes

2023-01-10 16:49 UTC, merged